# Site settings
title: "Gaurav's Portfolio & Blog"
description: "Machine Learning Engineer & Full Stack Developer"
baseurl: ""
url: "https://2796gaurav.github.io"
author: "Gaurav"
email: "gaurav@example.com"

# GitHub repository
repository: "2796gaurav/2796gaurav.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Gaurav"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .github/
  - notebooks/

# Animation settings
animation_enabled: true
particles_enabled: true
